
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/bar/nav";
import BottomBar from "@/components/bar/bottom"
import { Toaster } from "@/components/ui/toaster";
import { contactInfo, links } from '@/lib/BottomBarInfo'
import { AuthProvider } from "@/context/useAuth";
import { ProductProvider } from "@/context/useProduct";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
import { ThemeProvider } from "@/components/theme-provider"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <AuthProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <Navbar />
              <ProductProvider>
                {children}
              </ProductProvider>
              <Toaster />
              <BottomBar contactInfo={contactInfo} links={links} />
            </ThemeProvider>
          </AuthProvider>


      </body>
    </html >
  );
}
